### PR TITLE
Tracker Implementation with Snowplow Micro

### PR DESCRIPTION
**Pull request by teekaytech**
**In this PR, I implemented a Tracking Feature to my existing weather app.**

- This is a simple weather application that allows users to check the atmospheric condition of their current location. Kindly check the details of the project on the Readme.

**Please note**: the tracking feature is implemented in the `tracker-feature` branch, and the live demo of the app can be found [here](https://wappjs.netlify.app/).

_Thank you :blush:_

### CODE REVIEW

**Comment by paulboocock** [comment]
Hey @teekaytech Please remove the details above. I've copied them and wouldn't want others to find those, mainly for fear of increasing your AWS bill. I'll add another comment once I've completed my review so you can tear down the infrastructure.

**Comment by teekaytech** [comment]
> Hey @teekaytech Please remove the details above. I've copied them and wouldn't want others to find those, mainly for fear of increasing your AWS bill. I'll add another comment once I've completed my review so you can tear down the infrastructure. 

Hi @paulboocock,

Thank you for your feedback and guidance.
I'll remove them right away.

**Comment by paulboocock** [comment]
If you'd like to spin down the infrastructure to reduce your AWS bill, then feel free to do so, I've finished my review. We will be in contact soon.

**Comment by teekaytech** [comment]
> If you'd like to spin down the infrastructure to reduce your AWS bill, then feel free to do so, I've finished my review. We will be in contact soon.

Thank you.

**Pull request closed without merging**
